
http://localhost:3001/api/ping HTTP/1.1

###

http://localhost:3001/api/diagnoses HTTP/1.1

###

http://localhost:3001/api/patients HTTP/1.1
###

http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667 HTTP/1.1


###

POST http://localhost:3001/api/patients HTTP/1.1
content-type: application/json

{
  "name": "Testi Ukko 2",
  "occupation": "Coding dude",
  "ssn": "2134-3",
  "dateOfBirth": "1988-10-10",
  "gender": "väärä"
}

###

POST http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667/entries HTTP/1.1
content-type: application/json

{
  "date": "1988-12-24",
  "type": "Hospital",
  "specialist": "MC Henri",
  "diagnosisCodes": [
    "S62.5"
  ],
  "description": "SHATTERED GLASS EVERYWHERE",
  "discharge": {
    "date": "1988-12-25",
    "criteria": "Thumb has healed."
  }
}
