
http://localhost:3001/api/ping HTTP/1.1

###

http://localhost:3001/api/diagnoses HTTP/1.1

###

http://localhost:3001/api/patients HTTP/1.1

###

POST http://localhost:3001/api/patients HTTP/1.1
content-type: application/json

{
  "name": "Testi Ukko 2",
  "occupation": "Coding dude",
  "ssn": "2134-3",
  "dateOfBirth": "1988-10-10",
  "gender": "väärä"
}
